jobs:
  Issue template:
    name: Setup github issue templates
    paths: .neo/**/assets/templates/ISSUE_TEMPLATE/*.md
    steps:
      - name: Issue templates
        uses: copy
        with:
          output: .github/ISSUE_TEMPLATE
  PR template:
    name: Setup github pr templates
    paths: .neo/**/assets/templates/*.md
    steps:
      - name: PR templates
        uses: copy
        with:
          output: .github
  CI:
    name: Setup ci workflow
    paths: .neo/**/assets/workflows/*
    steps:
      - name: CI Workflows
        uses: copy
        with:
          output: .github/workflows
  Lint:
    name: Setup eslint
    paths: .neo/**/assets/eslint/.*
    steps:
      - name: ESLint
        uses: copy
          
  Setup Pkg:
    paths: package.json
    name: Setup lint config
    steps:
      - name: Add CI Scripts
        uses: json-editor
        with:
          pairs:
            - path: "scripts.ci:version"
              value: "pnpm changeset version"
            - path: "scripts.ci:publish"
              value: "pnpm run build && pnpm changeset publish"
            - path: "scripts.ci:snapshot"
              value: "pnpm changeset version --snapshot beta"
            - path: "scripts.ci:prerelease"
              value: "pnpm run build && pnpm changeset publish --tag beta"
      - name: Add lint-staged
        uses: json-editor
        with:
          pairs:
            - path: "lint-staged"
              value:
                "**/**/*.{js,ts,tsx,vue,json,yml,yaml}": ["eslint --fix"]

      - name: Add lint pkgs
        uses: json-editor
        with:
          pairs:
            - path: "devDependencies.typescript"
              value: "^4.6.4"
            - path: "devDependencies.eslint"
              value: "^8.32.0"
            - path: "devDependencies.@aiou/eslint-config"
              value: "^0.7.1"
            - path: "devDependencies.lint-staged"
              value: "^13.1.0"

      - name: Add changeset
        uses: json-editor
        with:
          pairs:
            - path: "devDependencies.@changesets/cli"
              value: "^2.26.0"

      - name: Add husky
        uses: json-editor
        with:
          pairs:
            - path: "devDependencies.husky"
              value: "^8.0.3"

      - name: Add lint:fix
        uses: json-editor
        with:
          pairs:
            - path: "scripts.lint:fix"
              value: "eslint . --fix"
  Changeset:
    name: Setup Changeset
    paths: .neo/**/assets/changeset/*
    steps:
      - name: Setup changeset
        uses: copy
        with:
          output: .changeset

  Precommit:
    paths: .git
    name: Setup precommit
    steps:
      - name: Setup Husky
        run: pnpx husky-init --yes
        continue-on-error: true
        with:
          quiet: true