jobs:
  issue template:
    name: Setup github issue templates
    paths: .neo/**/assets/templates/ISSUE_TEMPLATE/*.md
    steps:
      - name: Issue templates
        uses: copy
        with:
          output: .github/ISSUE_TEMPLATE
  pr template:
    name: Setup github pr templates
    paths: .neo/**/assets/templates/*.md
    steps:
      - name: PR templates
        uses: copy
        with:
          output: .github
  workflows:
    name: Setup workflow
    paths: .neo/**/assets/workflows/*
    steps:
      - name: CI Workflows
        uses: copy
        with:
          output: .github/workflows
  lint:
    name: Setup eslint
    paths: .neo/**/assets/eslint/eslint.config.js
    steps:
      - name: ESLint
        uses: copy
          
  setup package:
    paths: package.json
    name: Setup lint config
    steps:
      - name: Add CI Scripts
        uses: json-editor
        with:
          pairs:
            - path: "scripts.ci:version"
              value: "pnpm changeset version"
            - path: "scripts.ci:publish"
              value: "pnpm run build && pnpm changeset publish"
            - path: "scripts.ci:snapshot"
              value: "pnpm changeset version --snapshot snapshot"
            - path: "scripts.ci:prerelease"
              value: "pnpm run build && pnpm changeset publish --no-git-tag --snapshot"
      - name: Add lint-staged
        uses: json-editor
        with:
          pairs:
            - path: "lint-staged"
              value:
                "**/**/*.{js,ts,tsx,json,yml,yaml,md}": ["eslint --fix"]

      - name: Add lint pkgs
        uses: json-editor
        with:
          pairs:
            - path: "devDependencies.typescript"
              value: "^5.9.0"
            - path: "devDependencies.eslint"
              value: "^8.56.0"
            - path: "devDependencies.@aiou/eslint-config"
              value: "^1.5.1"
            - path: "devDependencies.lint-staged"
              value: "^13.1.0"

      - name: Add changeset
        uses: json-editor
        with:
          pairs:
            - path: "devDependencies.@changesets/cli"
              value: "^2.26.0"

      - name: Add husky
        uses: json-editor
        with:
          pairs:
            - path: "devDependencies.husky"
              value: "^8.0.3"

      - name: Add lint:fix
        uses: json-editor
        with:
          pairs:
            - path: "scripts.lint:fix"
              value: "eslint . --fix"
  changeset:
    name: Setup Changeset
    paths: .neo/**/assets/changeset/*
    steps:
      - name: Setup changeset
        uses: copy
        with:
          output: .changeset

  husky:
    paths: .neo/**/assets/husky/**
    name: Copy husky scripts
    steps:
      - name: Setup Husky
        uses: copy
        with:
          output: .husky
  prepare husky:
    paths: package.json
    name: Prepare husky script
    steps:
      - name: Add husky prepare scripts
        uses: json-editor
        with:
          pairs:
            - path: "scripts.prepare"
              value: "husky install"
  config commitizen:
    paths: .neo/**/assets/cz-emoji/.czrc
    name: Setup Commitizen
    steps:
      - name: Config Commitizen
        uses: copy
        with:
          output: .
  cz-emoji:
    paths: package.json
    name: Install cz-emoji
    steps:
      - name: Add cz-emoji
        uses: json-editor
        with:
          pairs:
            - path: "devDependencies.cz-emoji"
              value: "^1.3.1"