describe('command create', () => {
  it.todo('create bin-template')
  it.todo('create react-template')
  it.todo('create alfred-workflow-template')
  it.todo('create chrome-extension-template')
  it.todo('create dayjs-plugin-template')
  it.todo('create eslint-config-template')
  it.todo('create original-html-template')
  it.todo('create react-components-lib-template')
  it.todo('create rollup-template')
  it.todo('create ts-lib-template')
  it.todo('create webpack-loader-template')
})
