name: 🐛 Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
      render: Markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      placeholder: | 
        Steps to reproduce the behavior
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: Markdown
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: What version of our software are you running?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: OS
      options:
        - MacOS
        - Window
        - Linux
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      render: Markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      render: Markdown
    validations:
      required: false