jobs:
  Replace outdated:
    name: Replace outdated
    steps:
      - name: Replace outdated org
      - uses: replace
        with:
          match: spring-catponents
          replacement: neo-hack
      - name: Replace template name
      - uses: replace
        with:
          match: webext-template
          replacement: ${{ inputs.project }}

  Package:
    name: Package setup
    paths: package.json
    steps:
      - name: Reset version
      - uses: json-editor
        with:
          pairs:
            - path: "version"
              value: "0.0.0"
      - name: Setup project name
      - uses: json-editor
        with:
          pairs:
            - path: "name"
              value: ${{ inputs.project }}

  Clear unused files:
    name: clear unused files
    paths: templates/**
    steps:
      - name: clear templates
      - uses: clear