name: Node.js CI

on:
  push:
    paths:
      - 'packages/dayjs-template/**'
    branches: [master]
  pull_request:
    paths:
      - 'packages/dayjs-template/**'
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Rollup template

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.14.js | node - add --global pnpm@6
      - name: Install 
        run: |
          pnpm i --filter=./packages/dayjs-template
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Test
        working-directory: ./packages/dayjs-template
        run: |
          pnpm test
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
