on:
  push:
    paths:
      - 'packages/core/**'
  pull_request:
    paths:
      - 'packages/core/**'

jobs:
  build:
    runs-on: 'ubuntu-18.04'
    strategy:
      matrix:
        # pin node version: https://github.com/JiangWeixian/esrua/issues/12
        node-version: [14, 16.13.1]
    name: NEO
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install
        run: |
          pnpm install --frozen-lockfile=false
      - name: Build
        run: |
          pnpm run build
      - name: Test
        run: |
          pnpm run test
