on:
  push:
    paths:
      - 'packages/core/**'
    branches: [master]
  pull_request:
    paths:
      - 'packages/core/**'
    branches: [master]

jobs:
  build:
    runs-on: 'ubuntu-18.04'
    name: Cli extensions
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        run: |
          yarn
        working-directory: ./packages/core
      - name: Build
        run: |
          yarn build
          yarn test
        working-directory: ./packages/core
